import XCTest
@testable import Glucose

/// Replays fixtures generated by running the REAL engine.js
/// (`scripts/generate-parity-fixtures.js`) against the Swift port and
/// requires every output to match — this is what distinguishes "ported"
/// from "rewritten with a subtle bug". Regenerate the fixture file with:
///
///   node scripts/generate-parity-fixtures.js > ios/GlucoseEngineTests/Fixtures/parity-fixtures.json
///
/// whenever engine.js or medicalMath.js changes.
///
/// Dosing only: the fixture file also contains alarm scenarios, but the
/// app's alarm rules now diverge from engine.js on purpose — those are
/// covered by AlarmRulesTests.
final class DosingEngineParityTests: XCTestCase {

    // Rounded values in the JS fixtures are already 2-decimal; allow a
    // little slack for floating-point noise across platforms/libm.
    private let eps = 1e-6

    private func loadFixtures() throws -> ParityFixtures {
        let bundle = Bundle(for: Self.self)
        guard let url = bundle.url(forResource: "parity-fixtures", withExtension: "json", subdirectory: "Fixtures")
            ?? bundle.url(forResource: "parity-fixtures", withExtension: "json")
        else {
            XCTFail("parity-fixtures.json not found in test bundle")
            throw URLError(.fileDoesNotExist)
        }
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(ParityFixtures.self, from: data)
    }

    func testBolusRecommendationParity() throws {
        let fixtures = try loadFixtures()
        XCTAssertFalse(fixtures.bolusScenarios.isEmpty)

        for scenario in fixtures.bolusScenarios {
            let input = scenario.input
            let got = DosingEngine.recommendBolus(
                bg: input.bg,
                carbsG: input.carbsG,
                fpu: input.fpu,
                doses: input.doses,
                meals: input.meals,
                icr: input.icr,
                isf: input.isf,
                now: input.now,
                profile: input.profile
            )
            let want = scenario.result

            XCTAssertEqual(got.iob, want.iob, accuracy: eps, "\(scenario.id): iob")
            XCTAssertEqual(got.cob, want.cob, accuracy: eps, "\(scenario.id): cob")
            XCTAssertEqual(got.eventualBg, want.eventualBg, accuracy: eps, "\(scenario.id): eventual_bg")
            XCTAssertEqual(got.mealUnits, want.mealUnits, accuracy: eps, "\(scenario.id): meal_units")
            XCTAssertEqual(got.correctionUnits, want.correctionUnits, accuracy: eps, "\(scenario.id): correction_units")
            XCTAssertEqual(got.totalUnitsUnrounded, want.totalUnitsUnrounded, accuracy: eps, "\(scenario.id): total_units_unrounded")
            XCTAssertEqual(got.recommendedUnits, want.recommendedUnits, accuracy: eps, "\(scenario.id): recommended_units")
            XCTAssertEqual(got.rescueCarbsG, want.rescueCarbsG, accuracy: eps, "\(scenario.id): rescue_carbs_g")
        }
    }
}

// MARK: - Fixture decoding

private struct ParityFixtures: Decodable {
    let bolusScenarios: [BolusScenario]
}

private struct BolusScenario: Decodable {
    let id: String
    let input: BolusInput
    let result: BolusResultFixture
}

private struct BolusInput: Decodable {
    let bg: Double
    let carbsG: Double
    let fpu: Double
    let doses: [DoseInput]
    let meals: [MealInput]
    let icr: Double
    let isf: Double
    let now: Double
    let profile: EngineProfile

    enum CodingKeys: String, CodingKey {
        case bg, carbsG = "carbs_g", fpu, doses, meals, icr, isf, now, profile
    }
}

private struct BolusResultFixture: Decodable {
    let iob: Double
    let cob: Double
    let eventualBg: Double
    let mealUnits: Double
    let correctionUnits: Double
    let totalUnitsUnrounded: Double
    let recommendedUnits: Double
    let rescueCarbsG: Double

    enum CodingKeys: String, CodingKey {
        case iob, cob
        case eventualBg = "eventual_bg"
        case mealUnits = "meal_units"
        case correctionUnits = "correction_units"
        case totalUnitsUnrounded = "total_units_unrounded"
        case recommendedUnits = "recommended_units"
        case rescueCarbsG = "rescue_carbs_g"
    }
}
