import Foundation

/// Direct Swift port of `engine.js` — the deterministic dosing engine:
/// IOB, COB, bolus recommendation, rescue carbs, and treatment-aware
/// alarm suppression.
///
/// SAFETY PRINCIPLES (unchanged from the JS original)
/// - Pure functions only: same inputs -> same outputs, fully unit-testable.
/// - No AI, no randomness, no network. This module never depends on the
///   AI/chat layer.
/// - Doses round DOWN to the pen increment; rescue carbs round UP to 5 g.
///   When in doubt, err on the side of less insulin / more carbs.
/// - This engine SUGGESTS. The human decides.
///
/// The dosing math (IOB, COB, bolus, rescue carbs) must keep matching
/// engine.js. Verify with `DosingEngineParityTests`, which replays fixtures
/// generated by running the real engine.js
/// (`scripts/generate-parity-fixtures.js`) — that is what distinguishes
/// "ported" from "rewritten with a subtle bug". The alarm rules are the
/// exception: they now diverge on purpose (see MARK: - Alarms) and are
/// covered by `AlarmRulesTests` instead.
enum DosingEngine {

    // MARK: - IOB / COB passthroughs (see MedicalMath.swift)

    static func computeIOB(doses: [DoseInput], now: Double, profile: EngineProfile) -> Double {
        MedicalMath.computeIOB(doses: doses, now: now, profile: profile)
    }

    static func computeCOB(meals: [MealInput], now: Double, profile: EngineProfile) -> Double {
        MedicalMath.computeCOB(meals: meals, now: now, profile: profile)
    }

    // MARK: - Rounding

    static func roundDoseDown(_ units: Double, increment: Double) -> Double {
        max(0, (units / increment + 1e-9).rounded(.down) * increment)
    }

    static func roundCarbsUp(_ grams: Double) -> Double {
        max(0, (grams / 5).rounded(.up) * 5)
    }

    /// `Math.round` semantics (floor(x + 0.5)), not Swift's default
    /// round-half-away-from-zero — matters for the .5 boundary on negatives.
    private static func jsRound(_ x: Double) -> Double {
        (x + 0.5).rounded(.down)
    }

    private static func round2(_ x: Double) -> Double {
        jsRound(x * 100) / 100
    }

    // MARK: - Bolus recommendation

    /// COB-aware bolus recommendation — fixes the common calculator flaw
    /// (double-penalizing insulin just injected for food just eaten).
    /// See engine.js for the eventualBG derivation.
    static func recommendBolus(
        bg: Double,
        carbsG: Double = 0,
        fpu: Double = 0,
        doses: [DoseInput] = [],
        meals: [MealInput] = [],
        icr: Double,
        isf: Double,
        now: Double,
        profile: EngineProfile
    ) -> BolusRecommendation {
        let iob = computeIOB(doses: doses, now: now, profile: profile)
        let cob = computeCOB(meals: meals, now: now, profile: profile)

        let eventualBG = bg - iob * isf + cob * (isf / icr)

        let mealUnits = carbsG / icr
        let correctionUnits = (eventualBG - profile.targetMgDl) / isf
        let totalUnits = mealUnits + correctionUnits

        let recommended = roundDoseDown(totalUnits, increment: profile.doseIncrementU)

        var result = BolusRecommendation(
            bg: bg,
            iob: round2(iob),
            cob: round2(cob),
            icr: icr,
            isf: isf,
            targetMgDl: profile.targetMgDl,
            eventualBg: jsRound(eventualBG),
            mealUnits: round2(mealUnits),
            correctionUnits: round2(correctionUnits),
            totalUnitsUnrounded: round2(totalUnits),
            recommendedUnits: recommended,
            rescueCarbsG: 0,
            newMeal: NewMeal(carbsG: carbsG, fpu: fpu)
        )

        // Predicted low: instead of insulin, suggest grams to eat.
        let projectedAfterMeal = eventualBG + (carbsG * isf) / icr
        if projectedAfterMeal < profile.lowAlarmMgDl {
            let deficit = profile.targetMgDl - projectedAfterMeal
            result.rescueCarbsG = roundCarbsUp((deficit * icr) / isf)
            result.recommendedUnits = 0
        }

        return result
    }

    // MARK: - Alarms
    //
    // App alarm rules — these deliberately diverge from the reference
    // engine.js (which only documents the dosing math).
    // One target range drives everything: low_alarm_mg_dl..high_alarm_mg_dl
    // (in the app, the configurable min/max), inclusive — the same range
    // the time-in-range %, chart lines and colors use.
    //   - Low: below the range; repeats every low_refire_min (15); still
    //     snoozed low_snooze_min after carbs; <= urgent_low never snoozed.
    //   - High: above the range, only if the last injection was
    //     > post_injection_wait_min (120) ago. No "rising despite insulin"
    //     escape.
    //   - Forecast: same 2 h condition; alarms when the projected BG (the
    //     eventualBG the "Baixa" screen shows) leaves the range.

    /// True when the last bolus/correction is recent enough that the
    /// insulin has not had time to act — highs and forecasts stay quiet.
    private static func withinPostInjectionWait(now: Double, lastDoseAt: Double?, profile: EngineProfile) -> Bool {
        guard let lastDoseAt else { return false }
        return (now - lastDoseAt) / 60000 < profile.postInjectionWaitMin
    }

    private static func firedRecently(now: Double, lastFiredAt: Double?, windowMin: Double) -> Bool {
        guard let lastFiredAt else { return false }
        return (now - lastFiredAt) / 60000 < windowMin
    }

    static func evaluateHighAlarm(
        bg: Double,
        now: Double,
        lastDoseAt: Double? = nil,
        lastFiredAt: Double? = nil,
        profile: EngineProfile
    ) -> AlarmResult {
        if bg <= profile.highAlarmMgDl {
            return AlarmResult(fire: false, reason: "below_threshold")
        }
        if firedRecently(now: now, lastFiredAt: lastFiredAt, windowMin: profile.alarmRefireMin) {
            return AlarmResult(fire: false, reason: "recently_fired")
        }
        if withinPostInjectionWait(now: now, lastDoseAt: lastDoseAt, profile: profile) {
            return AlarmResult(fire: false, reason: "snoozed_recent_injection")
        }
        return AlarmResult(fire: true, reason: "high")
    }

    /// Forecast alarm: `eventualBg` is the projection from recommendBolus
    /// with no new meal (BG − IOB·ISF + COB·ISF/ICR) — i.e. where the
    /// insulin and carbs/FPU still on board will take BG. Catches the late
    /// fat/protein rise while the current value still looks fine.
    static func evaluateForecastAlarm(
        eventualBg: Double,
        now: Double,
        lastDoseAt: Double? = nil,
        lastFiredAt: Double? = nil,
        profile: EngineProfile
    ) -> AlarmResult {
        let direction: String
        if eventualBg > profile.highAlarmMgDl {
            direction = "forecast_high"
        } else if eventualBg < profile.lowAlarmMgDl {
            direction = "forecast_low"
        } else {
            return AlarmResult(fire: false, reason: "in_range")
        }
        if withinPostInjectionWait(now: now, lastDoseAt: lastDoseAt, profile: profile) {
            return AlarmResult(fire: false, reason: "snoozed_recent_injection")
        }
        if firedRecently(now: now, lastFiredAt: lastFiredAt, windowMin: profile.alarmRefireMin) {
            return AlarmResult(fire: false, reason: "recently_fired")
        }
        return AlarmResult(fire: true, reason: direction)
    }

    /// Low alarm: eating carbs snoozes it for low_snooze_min. Below
    /// urgent_low_mg_dl, nothing ever suppresses it.
    static func evaluateLowAlarm(
        bg: Double,
        now: Double,
        lastCarbsAt: Double? = nil,
        lastFiredAt: Double? = nil,
        profile: EngineProfile
    ) -> AlarmResult {
        if bg >= profile.lowAlarmMgDl {
            return AlarmResult(fire: false, reason: "above_threshold")
        }

        if bg <= profile.urgentLowMgDl {
            return AlarmResult(fire: true, reason: "urgent_low") // never suppressed
        }

        if firedRecently(now: now, lastFiredAt: lastFiredAt, windowMin: profile.lowRefireMin) {
            return AlarmResult(fire: false, reason: "recently_fired")
        }

        if let lastCarbsAt {
            let sinceCarbs = (now - lastCarbsAt) / 60000
            if sinceCarbs < profile.lowSnoozeMin {
                return AlarmResult(fire: false, reason: "snoozed_recent_carbs")
            }
        }

        return AlarmResult(fire: true, reason: "low")
    }
}

// MARK: - Inputs

struct DoseInput: Decodable {
    let units: Double
    let type: String
    let injectedAt: Double

    enum CodingKeys: String, CodingKey {
        case units, type
        case injectedAt = "injected_at"
    }
}

struct MealInput: Decodable {
    let carbsG: Double
    let fpu: Double?
    let eatenAt: Double

    enum CodingKeys: String, CodingKey {
        case carbsG = "carbs_g"
        case fpu
        case eatenAt = "eaten_at"
    }
}

/// Resolved profile — the dosing fields merge the stored profile over
/// engine.js's DEFAULTS, mirroring `resolveProfile()` (decoded from the
/// bolus parity fixtures). The alarm fields at the bottom are app-only
/// rules and are not decoded.
struct EngineProfile: Decodable {
    var diaHours: Double = 3.5
    var insulinPeakMin: Double = 75
    var targetMgDl: Double = 110
    /// engine.js names/defaults (kept for the parity fixtures). In the app
    /// these carry the configurable target range — see StoredTherapyProfile.
    var lowAlarmMgDl: Double = 70
    var highAlarmMgDl: Double = 240
    var urgentLowMgDl: Double = 55

    var carbAbsorptionGPerH: Double = 30
    var carbDelayMin: Double = 15
    var fpuDelayMin: Double = 120
    var fpuCarbEquivalentG: Double = 10

    var doseIncrementU: Double = 0.5

    var lowSnoozeMin: Double = 20
    var alarmRefireMin: Double = 30

    var lowRefireMin: Double = 15
    var postInjectionWaitMin: Double = 120

    enum CodingKeys: String, CodingKey {
        case diaHours = "dia_hours"
        case insulinPeakMin = "insulin_peak_min"
        case targetMgDl = "target_mg_dl"
        case lowAlarmMgDl = "low_alarm_mg_dl"
        case highAlarmMgDl = "high_alarm_mg_dl"
        case urgentLowMgDl = "urgent_low_mg_dl"
        case carbAbsorptionGPerH = "carb_absorption_g_per_h"
        case carbDelayMin = "carb_delay_min"
        case fpuDelayMin = "fpu_delay_min"
        case fpuCarbEquivalentG = "fpu_carb_equivalent_g"
        case doseIncrementU = "dose_increment_u"
        case lowSnoozeMin = "low_snooze_min"
        case alarmRefireMin = "alarm_refire_min"
    }

    init() {}

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        let d = EngineProfile()
        diaHours = try c.decodeIfPresent(Double.self, forKey: .diaHours) ?? d.diaHours
        insulinPeakMin = try c.decodeIfPresent(Double.self, forKey: .insulinPeakMin) ?? d.insulinPeakMin
        targetMgDl = try c.decodeIfPresent(Double.self, forKey: .targetMgDl) ?? d.targetMgDl
        lowAlarmMgDl = try c.decodeIfPresent(Double.self, forKey: .lowAlarmMgDl) ?? d.lowAlarmMgDl
        highAlarmMgDl = try c.decodeIfPresent(Double.self, forKey: .highAlarmMgDl) ?? d.highAlarmMgDl
        urgentLowMgDl = try c.decodeIfPresent(Double.self, forKey: .urgentLowMgDl) ?? d.urgentLowMgDl
        carbAbsorptionGPerH = try c.decodeIfPresent(Double.self, forKey: .carbAbsorptionGPerH) ?? d.carbAbsorptionGPerH
        carbDelayMin = try c.decodeIfPresent(Double.self, forKey: .carbDelayMin) ?? d.carbDelayMin
        fpuDelayMin = try c.decodeIfPresent(Double.self, forKey: .fpuDelayMin) ?? d.fpuDelayMin
        fpuCarbEquivalentG = try c.decodeIfPresent(Double.self, forKey: .fpuCarbEquivalentG) ?? d.fpuCarbEquivalentG
        doseIncrementU = try c.decodeIfPresent(Double.self, forKey: .doseIncrementU) ?? d.doseIncrementU
        lowSnoozeMin = try c.decodeIfPresent(Double.self, forKey: .lowSnoozeMin) ?? d.lowSnoozeMin
        alarmRefireMin = try c.decodeIfPresent(Double.self, forKey: .alarmRefireMin) ?? d.alarmRefireMin
    }
}

// MARK: - Outputs

struct NewMeal: Equatable {
    let carbsG: Double
    let fpu: Double
}

struct BolusRecommendation: Equatable {
    let bg: Double
    let iob: Double
    let cob: Double
    let icr: Double
    let isf: Double
    let targetMgDl: Double
    let eventualBg: Double
    let mealUnits: Double
    let correctionUnits: Double
    let totalUnitsUnrounded: Double
    var recommendedUnits: Double
    var rescueCarbsG: Double
    let newMeal: NewMeal
}

struct AlarmResult: Equatable {
    let fire: Bool
    let reason: String
}
